name: Desplegar la pagina

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Configurar node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile
      - name: Compilar página
        run: pnpm build
      - name: Copiar index a 404
        run: cp dist/haz-capturas/index.html dist/haz-capturas/404.html
      - name: Copiar sitemap
        run: cp src/sitemap.xml dist/haz-capturas/sitemap.xml
      - name: Copiar robots.txt
        run: cp src/robots.txt dist/haz-capturas/robots.txt
      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/haz-capturas

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
